version: '3'
services:

  # Spanner
  spanner:
    image: gcr.io/cloud-spanner-emulator/emulator:1.2.0
    container_name: spanner-emulator
    ports:
      - "9010:9010"
      - "9020:9020"

  # Init (Create Instance)
  gcloud-spanner-init:
    image: gcr.io/google.com/cloudsdktool/cloud-sdk:332.0.0-slim
    command: >
      bash -c 'gcloud config configurations create emulator &&
              gcloud config set auth/disable_credentials true &&
              gcloud config set project $${PROJECT_ID} &&
              gcloud config set api_endpoint_overrides/spanner $${SPANNER_EMULATOR_URL} &&
              gcloud config set auth/disable_credentials true &&
              gcloud spanner instances create $${INSTANCE_NAME} --config=emulator-config --description=Emulator --nodes=1'
    environment:
      PROJECT_ID: "test-project"
      SPANNER_EMULATOR_URL: "http://spanner-emulator:9020/"
      INSTANCE_NAME: "test-instance"
      DATABASE_NAME: "test-database"

  # DB Migration (Create Table)
  wrench-crearte:
    image: mercari/wrench:1.0.3
    command: "create --directory /ddl"
    environment:
      SPANNER_PROJECT_ID: "test-project"
      SPANNER_INSTANCE_ID: "test-instance"
      SPANNER_DATABASE_ID: "test-database"
      SPANNER_EMULATOR_HOST: "spanner-emulator:9010"
    volumes:
      - ../db/ddl/transaction/init.gen.sql:/ddl/schema.sql
    restart: on-failure

  # CLI
  spanner-cli:
    image: sjdaws/spanner-cli:v1.0.0
    environment:
      SPANNER_EMULATOR_HOST: "spanner-emulator:9010"
    command: ['sh', '-c', 'echo this container keep running && tail -f /dev/null']
