// Code generated by protoc-gen-all. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

//go:generate mockgen -source=$GOFILE -destination=mock_$GOPACKAGE/mock_user.go
//go:generate goimports -w --local "github.com/xhayamix/proto-gen-spanner" mock_$GOPACKAGE/mock_user.go

package transaction

import (
	"context"

	"github.com/xhayamix/proto-gen-spanner/pkg/domain/database"
	"github.com/xhayamix/proto-gen-spanner/pkg/domain/entity/transaction"
)

type UserRepository interface {
	LoadByPK(ctx context.Context, tx database.ROTx, key *transaction.UserPK) (*transaction.User, error)
	LoadByPKs(ctx context.Context, tx database.ROTx, keys transaction.UserPKs) (transaction.UserSlice, error)
	SelectByPK(ctx context.Context, tx database.ROTx, key *transaction.UserPK) (*transaction.User, error)
	SelectByPKs(ctx context.Context, tx database.ROTx, keys transaction.UserPKs) (transaction.UserSlice, error)
	// SelectAll not use cache. ReadOnlyTx時のみ使用可能
	SelectAll(ctx context.Context, tx database.ROTx, limit, offset int32) (transaction.UserSlice, error)
	// Search not use cache. ReadOnlyTx時のみ使用可能
	Search(ctx context.Context, tx database.ROTx, search string, limit, offset int32) (transaction.UserSlice, error)
	Insert(ctx context.Context, tx database.RWTx, entity *transaction.User) error
	BulkInsert(ctx context.Context, tx database.RWTx, entities transaction.UserSlice) error
	Update(ctx context.Context, tx database.RWTx, entity *transaction.User) error
	Save(ctx context.Context, tx database.RWTx, entity *transaction.User) error
	Delete(ctx context.Context, tx database.RWTx, key *transaction.UserPK) error
	BulkDelete(ctx context.Context, tx database.RWTx, keys transaction.UserPKs) error
}
