// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"context"
	"github.com/xhayamix/proto-gen-spanner/cmd/di/provider"
	user3 "github.com/xhayamix/proto-gen-spanner/pkg/cmd/api/handler/user"
	user2 "github.com/xhayamix/proto-gen-spanner/pkg/cmd/api/intaractor/user"
	"github.com/xhayamix/proto-gen-spanner/pkg/domain/service/user"
	"github.com/xhayamix/proto-gen-spanner/pkg/infra/transaction"
	"github.com/xhayamix/proto-gen-spanner/pkg/infra/transaction/repository"
)

// Injectors from wire.go:

func InitializeApp(ctx context.Context) (*provider.App, error) {
	client, err := spanner.New(ctx)
	if err != nil {
		return nil, err
	}
	txManager := spanner.NewSpannerUserTxManager(client)
	userRepository := repository.NewUserRepository()
	service := user.New(userRepository)
	interactor := user2.New(txManager, service)
	userServer := user3.New(interactor)
	app := provider.NewApp(userServer, client)
	return app, nil
}
