// Code generated by protoc-gen-all. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package converter

type EntityConverter interface {
}

type entityConverter struct{}

func newEntityConverter() *entityConverter {
	return &entityConverter{}
}
