// Code generated by protoc-gen-all. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package converter

type PKConverter interface {
}

type pkConverter struct{}

func NewPKConverter() PKConverter {
	return &pkConverter{}
}
