// Code generated by protoc-gen-all. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package converter

func toInt32Slice(s []int64) []int32 {
	ret := make([]int32, 0, len(s))

	for _, v := range s {
		ret = append(ret, int32(v))
	}

	return ret
}
